Rewrite `set-theme` to avoid file corruption
nickjj/dotfiles pull request #9
Opened 2021-01-23 13:04 UTC by shayaviv

With these changes, `set-theme --toggle-bg` should toggle the background for the active theme.
These changes also reduces the memory usage, since only one line is read (and written) at a time.

2021-01-23 13:47 UTC, nickjj commented
Hi,

Thanks a lot for the patch.

As for the new implementation, aren't we making a pretty big trade off here too? Now it scans the file from top to bottom line by line looking for matches to write and then it writes the changes as it finds the matches. I haven't used fileinput before. But the code looks like it might still be writing to the file multiple files? Does `sys.stdout.write(line)` perform the write at that point?

I also wonder if there's any readable patterns we can use to de-dupe the set up around using fileinput. Basically abstract the concept of using it to do inplace edits on a file and loop over each line. This way we only need to pass in what's being replaced.

2021-01-23 14:48 UTC, shayaviv commented
Hi Nick - thanks for considering my patch.

Yes, `sys.stdout.write(line)` performs the (buffered) write to the file. I still think it's a considerable improvement because the file is written then closed only once. As a result, if some process listens to an `IN_CLOSE_WRITE` event (or the like), that event will only trigger once. With the existing code, files are written and closed multiple times.

As for de-duping, we can define something like this:
```python
def inplace_edit(file):
    return fileinput.input(files=(file,), inplace=True)
```
then use it like this:
```python
with inplace_edit(MYFILE) as f:
    for line in f:
        process(line)
```
where `process(line)` writes to stdout using `sys.stdout.write` or just `print`.

2021-01-23 15:24 UTC, nickjj commented
Oh I see.

So in the old case it's doing an open + close + [update content] + write + close and now it's just doing an open + close while 0 or more writes happen while it's open?

And the corruption happens with the old code because that close event is happening twice and it's too quick for the MS terminal to deal with it due to the way it's listening for changes? It most likely does watch that config file because updating the config will have its effects take place within a reasonable amount of time (100-200ms).

Are we still at a risk for corruption with the new code if the MS terminal happens to poll the file while it's open during the inplace_edit?

2021-01-23 17:03 UTC, shayaviv commented
There's no harm in doing: open (`r` mode) -> read contents -> close. I believe the problem with the existing code is that the following is done **twice**: open (`w` mode) -> write contents -> close.

The first write is this line: https://github.com/nickjj/dotfiles/blob/42be51f9fd2e7a48ec88b1bf79854e6c279f97db/.local/bin/set-theme#L199 and the second write is this line: https://github.com/nickjj/dotfiles/blob/42be51f9fd2e7a48ec88b1bf79854e6c279f97db/.local/bin/set-theme#L128

<table>
<caption>Here's a timeline of what I suspect is going on:</caption>
<tr>
<th>set-theme</th>
<th>Windows Terminal</th>
</tr>
<tr>
<td>Open <code>settings.json</code> (<code>r</code> mode)</td>
<td rowspan="5">Wait for <code>settings.json</code> to change</td>
</tr>
<tr>
<td>Read contents of <code>settings.json</code></td>
</tr>
<tr>
<td>Close <code>settings.json</code></td>
</tr>
<tr>
<td>Open <code>settings.json</code> (<code>w</code> mode)</td>
</tr>
<tr>
<td>Write contents of <code>settings.json</code></td>
</tr>
<tr>
<td>Close <code>settings.json</code></td>
<td rowspan="2">
The file has changed (closed after writing).<br/>
Start reading <code>settings.json</code>
</td>
</tr>
<tr>
<td>Open <code>settings.json</code> (<code>w</code> mode)</td>
</tr>
<tr>
<td>Write contents of <code>settings.json</code></td>
<td>Read corrupted data (modified while reading)</td>
</tr>
<tr>
<td>Close <code>settings.json</code></td>
<td></td>
</tr>
</table>

2021-01-23 17:19 UTC, nickjj commented
Thanks for the break down.

Let's get this merged, but it may involve a few minor formatting changes, splitting up commits, etc..

I'll address these in a review on some of the lines over the next couple of days.

I know some low hanging fruit will be adding 1 space between defining a variable and executing a block of code below it. There's also making that `inplace_edit` change. I guess it might get too tricky using yield to include the for loop in the function too?

2021-01-23 18:34 UTC, nickjj commented
You're making this too easy haha. Those are really good.

Btw do you have a TL;DR on `store_true` and how it differs from the old set up? I haven't pulled down your branch yet to try it out.

2021-01-23 18:42 UTC, shayaviv commented
Thanks 😄

`action='store_true'` is equivalent to `action='store_const', const=True, default=False`

2021-01-23 22:29 UTC, nickjj commented
One difference I noticed is:

New version: if you run `set-theme` with no arguments it reports no output with an exit code 0.
Old version: if you run `set-theme` with no arguments it throws a theme required error with an exit code 2.

Although this has kind of a nice side effect of being able to run `set-theme --toggle-bg` if you want to toggle the bg of the current theme without having to explicitly put the theme name in even if it doesn't change.

I'm going to leave this thing in a 100ms loop for the next hour and see if it corrupts anything.

2021-01-24 07:06 UTC, shayaviv commented
Thanks for the observation. I added a check which prints an error (with exit code 2) when no arguments are given.

Another thing I noticed is that `edit_inplace` will replace symlinks. So after running `set-theme`, `.vimrc` (for example) is no longer symlinked to `~/dotfiles/.vimrc`. I don't know if it was like that before. If we want to preserve symlinks, I suggest to modify `edit_inplace` like this:
```diff
@@ -83,5 +83,5 @@ VIM_CONFIG = f'{HOME}/.vimrc'
 
 def edit_inplace(file):
-    return fileinput.input(files=(file,), inplace=True)
+    return fileinput.input(files=(os.path.realpath(file),), inplace=True)
 
```

2021-01-24 12:51 UTC, nickjj commented
The original kept the symlink in tact. Good catch tho, I didn't check for that in your version but I did have similar logic with the old `sed` commands before this was a Python script.

Can you amend these commits:

Feel free to amend 57c2df1 with your proposed `edit_inplace` change but you'll need to import os too.

For be4e66e it might also be worth changing the argparse condition to check the length of `args` to see if it's empty (or 1, whatever the case is for not including args). This way we don't have to hard code the arguments. What do you think?

In 48482bd I noticed you're using `exit()` instead of `sys.exit()`. Should we stick with using `sys.exit()`? The docs mention passing in a string will result in an exit code of 1 so we should be good to go.

2021-01-24 16:12 UTC, shayaviv commented
Right, passing a string to `exit()` will print the string to `sys.stderr` and call `sys.exit(1)`, which is what we want. But we can call `sys.stderr.write(errormsg)` and `sys.exit(1)` explicitly if you prefer.

I amended 57c2df1 with my proposed `edit_inplace` to preserve symlinks.

I also pushed b932f9fdf2 to check the length of `args` instead of hard-coding the arguments.

2021-01-24 16:15 UTC, nickjj commented
I think we can get by with just calling `sys.exit("foo")` based on the Python docs of:

> and if any other object is printed to stderr and results in an exit code of 1. In particular, sys.exit("some error message") is a quick way to exit a program when an error occurs.

2021-01-24 16:20 UTC, shayaviv commented
`sys.exit()` does indeed print to `sys.stderr` when passed a string:
```
$ python3 -c 'import sys; sys.exit("bye")' > /dev/null
bye

$ echo $?
1
```
I also prefer `sys.exit()` over `exit()`, so let's use that.

2021-01-24 16:30 UTC, nickjj commented
Could we use this newfound knowledge of `sys.exit()` to amend https://github.com/nickjj/dotfiles/pull/9/commits/2d938dc2be6461e3ec63ea94a11cb0b369cd3bf1 by removing the `print` call and passing that error message directly to sys.exit? I'm ok with it returning 1 instead of 2.

Also, I'm not in a position to test this now but what does `parser.print_usage()` do? Could that be removed too?

2021-01-24 16:37 UTC, shayaviv commented
I called `parser.print_usage(sys.stderr)` and `sys.exit(2)` just to imitate the way `argparse` handles errors. See https://github.com/python/cpython/blob/15bd9efd01e44087664e78bf766865a6d2e06626/Lib/argparse.py#L2573

2021-01-24 16:44 UTC, nickjj commented
Ok fair enough, let's keep it as is. Sometimes a bit of extra code is worth it to make the user experience better and more consistent.

One last thing, in https://github.com/nickjj/dotfiles/commit/b932f9fdf2a753631985425592fb4e81d6815ec8 you have `if not any(vars(args).values())`. Could this be also written as something like: `if len(sys.argv) == 1`? A length of 0 wouldn't ever happen since I think the script name will always be the first item in the list (not in a spot to run a Python REPL atm).

2021-01-24 18:18 UTC, shayaviv commented
`len(sys.argv) == 1` is definitely better, thanks. I decided to call `ArgumentParser.error()` directly - it is much cleaner:
> `ArgumentParser.error(message)`
> This method prints a usage message including the _message_ to the standard error and terminates the program with a status code of 2.

https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.error

2021-01-24 19:14 UTC, nickjj commented
Awesome thanks.

I'll pull this down and give it a run through a bit later today and then merge it in if all goes well (it should).

2021-01-24 19:50 UTC, shayaviv commented
I know my merge window is closing, but I had a great idea to make the argument parser more helpful (3692310):
```
$ ./set-theme foo
usage: set-theme [-h] [--toggle-bg] [THEME]
set-theme: error: argument THEME: invalid choice: 'foo' (choose from 'gruvbox', 'one')
```

2021-01-24 20:01 UTC, nickjj commented
Oh wow, I didn't even know argparse did that out of the box.

There's always time for deleting code.

2021-01-24 20:02 UTC, shayaviv commented
With d518236202725e6238f20719c781830fa40811e6, the themes are also listed automatically:
```
$ set-theme -h
usage: set-theme [-h] [--toggle-bg] [{gruvbox,one}]

Set a theme along with optionally toggling dark and light backgrounds.

positional arguments:
  {gruvbox,one}  the theme name

optional arguments:
  -h, --help     show this help message and exit
  --toggle-bg    toggle the background between dark and light
```

2021-01-24 20:11 UTC, shayaviv commented
About deleting code - I have to agree! I like to brag at work about my GitHub Enterprise stats - my deletions are roughly twice the amount of additions 😄

2021-01-24 21:35 UTC, nickjj commented
This PR deletes more code than adding it, so you're winning there considering how much better the script is now.

Can you amend 39904827cc086145cd62075df70648f0529ed5a4 by making the return and sys.exit lines be indented with 4 spaces instead of 2? It should pass running `flake8` against it.

2021-01-25 04:39 UTC, shayaviv commented
I also dropped 189354ae8bd0a4d5dd75c7b2b21d727573f5352e, as d518236 removes it anyway

2021-01-25 12:29 UTC, nickjj commented
I think we're ready for a final test run / merge?

2021-01-25 13:08 UTC, nickjj commented on .local/bin/set-theme
> +    return fileinput.input(files=(file,), inplace=True)
Can you add a new line above this line?

2021-01-25 13:09 UTC, nickjj commented on .local/bin/set-theme
> +            match = re.match('^colorscheme (.*$)$', line)
Can you add a new line above this line?

2021-01-25 13:11 UTC, nickjj commented on .local/bin/set-theme
> +            sys.stdout.write(line)
Can you add an empty new line above the write line?

2021-01-25 13:13 UTC, nickjj requested changes
I've left a few minor recommendations on formatting.

Can you please amend the commits they are associated to?

2021-01-25 13:56 UTC, shayaviv commented
I amended the commits to fix the formatting as you suggested. Please give this a final test - I have nothing more to add (or remove 🙂)

2021-01-25 14:13 UTC, merged

2021-01-25 14:13 UTC, nickjj commented
It's all good. Thanks a lot for the patch and for making the overall PR experience as good as it gets.